spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: 5b3c8931560d04387997
            client-secret: 5e6b461f457ef757c6df42a68d40bd172a1a8fe1
            redirectUri: "http://3.36.247.153:3000/login/oauth2/code/github"
            scope: user


  profiles:
    group:
      "local" : "local, jwt, oauth"
    active : local

---
spring:
  config:
    activate:
      on-profile: "local"

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://oauth.c9d71oyl8as0.ap-northeast-2.rds.amazonaws.com:3306/oauth
    username: admin
    password: 12345678

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true

    hibernate:
      ddl-auto: create
